#!/bin/bash

set -e

cd $WORKSPACE_ROOT_DIR

source venv/bin/activate

if (( $# )) ; then
  TARGETS=( $@ )
else
  TARGETS=( tapestry )
fi

echo "Code Quality Scans ..."

dmypy run --timeout 1200 -- "${TARGETS[@]}"

# does not like pytorch
# pyre incremental
